export const EVENTS = [
    {
      id: 1,
      title: "AI Revolution: LLMs & Future Tech",
      date: { day: "12", month: "OCT" },
      time: "09:00 AM - 11:30 AM",
      location: "Alpha Hall, FPT Hanoi",
      category: "WORKSHOP",
      status: "OPEN",
      isPopular: true,
      image: "https://picsum.photos/seed/ai-tech/800/600", 
    },
    {
      id: 2,
      title: "Guitar Club: Open Mic Night",
      date: { day: "14", month: "OCT" },
      time: "06:00 PM - 09:00 PM",
      location: "Student Center, FPT Hanoi",
      category: "CLUB",
      status: "FILLING FAST",
      isPopular: false,
      image: "https://picsum.photos/seed/guitar/800/600",
    },
    {
      id: 3,
      title: "FPT Career Fair 2024",
      date: { day: "01", month: "NOV" },
      time: "08:00 AM - 04:00 PM",
      location: "Main Auditorium, FPT HCM",
      category: "ACADEMIC",
      status: "OPEN",
      isPopular: false,
      image: "https://picsum.photos/seed/career/800/600",
    },
    {
      id: 4,
      title: "UI/UX Design Sprint",
      date: { day: "05", month: "NOV" },
      time: "02:00 PM - 05:00 PM",
      location: "Room 404, FPT Da Nang",
      category: "WORKSHOP",
      status: "OPEN",
      isPopular: false,
      image: "https://picsum.photos/seed/uiux/800/600", 
    },
    {
      id: 5,
      title: "3v3 Basketball Tournament",
      date: { day: "10", month: "OCT" },
      time: "07:00 AM - 01:00 PM",
      location: "Sports Field, FPT Hanoi",
      category: "SPORTS",
      status: "CLOSED",
      isPopular: false,
      image: "https://picsum.photos/seed/sports/800/600", 
    },
    {
      id: 6,
      title: "Public Speaking Masterclass",
      date: { day: "12", month: "NOV" },
      time: "10:00 AM - 12:00 PM",
      location: "Gamma Hall, FPT Hanoi",
      category: "SOFT SKILLS",
      status: "OPEN",
      isPopular: false,
      image: "https://picsum.photos/seed/speaking/800/600", 
    },
  ]
  
  export const CATEGORIES = [
    { id: "workshops", label: "Workshops", count: 12 },
    { id: "clubs", label: "Club Activities", count: 8 },
    { id: "academic", label: "Academic Seminars", count: 5 },
    { id: "sports", label: "Sports & E-sports", count: 3 },
  ]
  
  export const CAMPUSES = [
    { id: "all", label: "All Campuses" },
    { id: "hanoi", label: "FPT Hanoi" },
    { id: "danang", label: "FPT Da Nang" },
    { id: "hcm", label: "FPT Ho Chi Minh" },
  ]