import type { EventDetail } from "./types"

export const EVENTS = [
  {
    id: 1,
    slug: "ai-revolution",
    title: "AI Revolution: LLMs & Future Tech",
    date: { day: "12", month: "OCT" },
    time: "09:00 AM - 11:30 AM",
    location: "Alpha Hall, FPT Hanoi",
    category: "WORKSHOP",
    status: "OPEN",
    isPopular: true,
    image: "https://picsum.photos/seed/ai-tech/800/600",
  },
  {
    id: 2,
    slug: "guitar-open-mic",
    title: "Guitar Club: Open Mic Night",
    date: { day: "14", month: "OCT" },
    time: "06:00 PM - 09:00 PM",
    location: "Student Center, FPT Hanoi",
    category: "CLUB",
    status: "FILLING FAST",
    isPopular: false,
    image: "https://picsum.photos/seed/guitar/800/600",
  },
  {
    id: 3,
    slug: "career-fair-2024",
    title: "FPT Career Fair 2024",
    date: { day: "01", month: "NOV" },
    time: "08:00 AM - 04:00 PM",
    location: "Main Auditorium, FPT HCM",
    category: "ACADEMIC",
    status: "OPEN",
    isPopular: false,
    image: "https://picsum.photos/seed/career/800/600",
  },
  {
    id: 4,
    slug: "uiux-design-sprint",
    title: "UI/UX Design Sprint",
    date: { day: "05", month: "NOV" },
    time: "02:00 PM - 05:00 PM",
    location: "Room 404, FPT Da Nang",
    category: "WORKSHOP",
    status: "OPEN",
    isPopular: false,
    image: "https://picsum.photos/seed/uiux/800/600",
  },
  {
    id: 5,
    slug: "basketball-3v3",
    title: "3v3 Basketball Tournament",
    date: { day: "10", month: "OCT" },
    time: "07:00 AM - 01:00 PM",
    location: "Sports Field, FPT Hanoi",
    category: "SPORTS",
    status: "CLOSED",
    isPopular: false,
    image: "https://picsum.photos/seed/sports/800/600",
  },
  {
    id: 6,
    slug: "public-speaking-masterclass",
    title: "Public Speaking Masterclass",
    date: { day: "12", month: "NOV" },
    time: "10:00 AM - 12:00 PM",
    location: "Gamma Hall, FPT Hanoi",
    category: "SOFT SKILLS",
    status: "OPEN",
    isPopular: false,
    image: "https://picsum.photos/seed/speaking/800/600",
  },
]

export const EVENT_DETAILS: EventDetail[] = [
  {
    id: 1,
    slug: "ai-revolution",
    title: "AI Revolution: LLMs & Future Tech",
    date: "2026-10-12T09:00:00+07:00",
    timeRange: "09:00 AM - 12:10 PM",
    location: "Alpha Hall, FPT Hanoi",
    description:
      "A deep dive into large language models, agentic workflows, and real-world product demos from industry leaders. We'll cover retrieval strategies, evaluation, and how teams are shipping AI features safely at scale.",
    price: 0,
    totalSeats: 280,
    registeredSeats: 214,
    image: "https://picsum.photos/seed/ai-tech/1200/700",
    tags: ["Workshop", "AI", "LLMs", "Product", "Engineering"],
    takeaways: [
      "Map LLM architectures to practical use cases",
      "Compare RAG, tools, and fine-tuning tradeoffs",
      "Learn evaluation and safety guardrails",
      "Get a rollout checklist for AI features",
    ],
    schedule: [
      { time: "09:00 AM", title: "Check-in & Welcome Coffee" },
      {
        time: "09:25 AM",
        title: "Keynote: LLMs in 2026 and Beyond",
        description: "Dr. Nguyen Van A",
      },
      {
        time: "10:05 AM",
        title: "Deep Dive: RAG vs. Fine-tuning",
        description: "Tran Minh Khang",
      },
      {
        time: "10:40 AM",
        title: "Hands-on Lab: Build an Agentic Workflow",
        description: "Le Thanh Phuong",
      },
      { time: "11:35 AM", title: "Demo Session: AI in Production" },
      { time: "11:55 AM", title: "Live Q&A + Networking" },
    ],
    speakers: [
      {
        id: "spk-ai-1",
        name: "Dr. Nguyen Van A",
        role: "Head of AI Department",
        company: "FPT University",
        avatar: "https://i.pravatar.cc/160?img=32",
      },
      {
        id: "spk-ai-2",
        name: "Tran Minh Khang",
        role: "AI Product Lead",
        company: "FPT Software",
        avatar: "https://i.pravatar.cc/160?img=15",
      },
      {
        id: "spk-ai-3",
        name: "Le Thanh Phuong",
        role: "Research Engineer",
        company: "VinAI",
        avatar: "https://i.pravatar.cc/160?img=45",
      },
      {
        id: "spk-ai-4",
        name: "Nguyen Thao Linh",
        role: "ML Ops Engineer",
        company: "VNG",
        avatar: "https://i.pravatar.cc/160?img=24",
      },
    ],
    host: {
      name: "F-Code Club",
      avatar: "/f-code-logo.png",
    },
  },
  {
    id: 2,
    slug: "guitar-open-mic",
    title: "Guitar Club: Open Mic Night",
    date: "2026-10-14T18:00:00+07:00",
    timeRange: "06:00 PM - 09:00 PM",
    location: "Student Center, FPT Hanoi",
    description:
      "An acoustic evening for all levels. Bring your guitar, share your favorite songs, and enjoy live performances.",
    price: 0,
    totalSeats: 120,
    registeredSeats: 98,
    image: "https://picsum.photos/seed/guitar/1200/700",
    tags: ["Club", "Music", "Community"],
    takeaways: [
      "Jam with fellow musicians",
      "Discover new local talents",
      "Relax and connect after class",
    ],
    schedule: [
      { time: "06:00 PM", title: "Doors Open" },
      { time: "06:30 PM", title: "Open Mic Round 1" },
      { time: "07:30 PM", title: "Guest Performance" },
      { time: "08:15 PM", title: "Open Mic Round 2" },
    ],
    speakers: [
      {
        id: "spk-gtr-1",
        name: "Doan Thanh Dat",
        role: "Club Mentor",
        company: "Guitar Club",
        avatar: "https://i.pravatar.cc/160?img=25",
      },
      {
        id: "spk-gtr-2",
        name: "Vo Minh Anh",
        role: "Lead Performer",
        company: "Guitar Club",
        avatar: "https://i.pravatar.cc/160?img=48",
      },
    ],
    host: {
      name: "Guitar Club",
      avatar: "/f-code-logo.png",
    },
  },
  {
    id: 3,
    slug: "career-fair-2024",
    title: "FPT Career Fair 2024",
    date: "2026-11-01T08:00:00+07:00",
    timeRange: "08:00 AM - 04:00 PM",
    location: "Main Auditorium, FPT HCM",
    description:
      "Meet recruiters, explore internships, and attend career growth talks from leading tech companies.",
    price: 0,
    totalSeats: 400,
    registeredSeats: 356,
    image: "https://picsum.photos/seed/career/1200/700",
    tags: ["Career", "Networking", "Academic"],
    takeaways: [
      "Connect with hiring managers",
      "Improve your CV and portfolio",
      "Find internship opportunities",
    ],
    schedule: [
      { time: "08:00 AM", title: "Check-in & Company Booths" },
      { time: "10:00 AM", title: "Career Talk: Hiring Trends" },
      { time: "01:30 PM", title: "CV Clinic" },
      { time: "03:00 PM", title: "Networking Session" },
    ],
    speakers: [
      {
        id: "spk-cf-1",
        name: "Pham Thu Ha",
        role: "HR Manager",
        company: "FPT Software",
        avatar: "https://i.pravatar.cc/160?img=5",
      },
      {
        id: "spk-cf-2",
        name: "Vu Quang Huy",
        role: "Tech Recruiter",
        company: "VNG",
        avatar: "https://i.pravatar.cc/160?img=12",
      },
      {
        id: "spk-cf-3",
        name: "Dang Lan Phuong",
        role: "Career Coach",
        company: "TopCV",
        avatar: "https://i.pravatar.cc/160?img=8",
      },
    ],
    host: {
      name: "FPT Career Services",
      avatar: "/f-code-logo.png",
    },
  },
  {
    id: 4,
    slug: "uiux-design-sprint",
    title: "UI/UX Design Sprint",
    date: "2026-11-05T14:00:00+07:00",
    timeRange: "02:00 PM - 05:00 PM",
    location: "Room 404, FPT Da Nang",
    description:
      "Learn rapid ideation, prototyping, and user testing in a guided design sprint with industry designers.",
    price: 150000,
    totalSeats: 80,
    registeredSeats: 54,
    image: "https://picsum.photos/seed/uiux/1200/700",
    tags: ["Design", "Workshop", "UX"],
    takeaways: [
      "Build a sprint-ready workflow",
      "Practice rapid prototyping",
      "Collect user feedback effectively",
    ],
    schedule: [
      { time: "02:00 PM", title: "Sprint Kickoff" },
      { time: "02:30 PM", title: "Ideation & Sketching" },
      { time: "03:30 PM", title: "Prototype Building" },
      { time: "04:30 PM", title: "Testing & Debrief" },
    ],
    speakers: [
      {
        id: "spk-ui-1",
        name: "Pham Gia Han",
        role: "UX Designer",
        company: "NashTech",
        avatar: "https://i.pravatar.cc/160?img=22",
      },
      {
        id: "spk-ui-2",
        name: "Ngo Thu Trang",
        role: "Product Designer",
        company: "Tiki",
        avatar: "https://i.pravatar.cc/160?img=36",
      },
    ],
    host: {
      name: "FPT Design Hub",
      avatar: "/f-code-logo.png",
    },
  },
  {
    id: 5,
    slug: "basketball-3v3",
    title: "3v3 Basketball Tournament",
    date: "2026-10-10T07:00:00+07:00",
    timeRange: "07:00 AM - 01:00 PM",
    location: "Sports Field, FPT Hanoi",
    description:
      "Compete with top campus teams, win prizes, and enjoy an energetic morning of 3v3 basketball.",
    price: 50000,
    totalSeats: 96,
    registeredSeats: 96,
    image: "https://picsum.photos/seed/sports/1200/700",
    tags: ["Sports", "Tournament", "Community"],
    takeaways: [
      "Compete in a fast-paced 3v3 format",
      "Meet athletes across campuses",
      "Earn medals and prizes",
    ],
    schedule: [
      { time: "07:00 AM", title: "Warm-up & Check-in" },
      { time: "08:00 AM", title: "Group Stage" },
      { time: "10:30 AM", title: "Semi-finals" },
      { time: "11:30 AM", title: "Final Match" },
    ],
    speakers: [
      {
        id: "spk-bb-1",
        name: "Nguyen Duc Anh",
        role: "Coach",
        company: "FPT Sports",
        avatar: "https://i.pravatar.cc/160?img=18",
      },
    ],
    host: {
      name: "FPT Sports Club",
      avatar: "/f-code-logo.png",
    },
  },
  {
    id: 6,
    slug: "public-speaking-masterclass",
    title: "Public Speaking Masterclass",
    date: "2026-11-12T10:00:00+07:00",
    timeRange: "10:00 AM - 12:00 PM",
    location: "Gamma Hall, FPT Hanoi",
    description:
      "Sharpen your delivery, confidence, and storytelling with guided exercises and real-time feedback.",
    price: 0,
    totalSeats: 180,
    registeredSeats: 125,
    image: "https://picsum.photos/seed/speaking/1200/700",
    tags: ["Soft Skills", "Communication", "Workshop"],
    takeaways: [
      "Improve confidence and structure",
      "Practice with peer feedback",
      "Learn storytelling techniques",
    ],
    schedule: [
      { time: "10:00 AM", title: "Opening & Ice Breaker" },
      { time: "10:30 AM", title: "Storytelling Frameworks" },
      { time: "11:15 AM", title: "Live Practice" },
      { time: "11:50 AM", title: "Wrap-up" },
    ],
    speakers: [
      {
        id: "spk-ps-1",
        name: "Bui Thi Mai",
        role: "Communication Coach",
        company: "VietSkills",
        avatar: "https://i.pravatar.cc/160?img=30",
      },
      {
        id: "spk-ps-2",
        name: "Le Quoc Bao",
        role: "MC & Trainer",
        company: "Freelance",
        avatar: "https://i.pravatar.cc/160?img=11",
      },
    ],
    host: {
      name: "FPT Soft Skills Club",
      avatar: "/f-code-logo.png",
    },
  },
]

export const CATEGORIES = [
  { id: "workshops", label: "Workshops", count: 12 },
  { id: "clubs", label: "Club Activities", count: 8 },
  { id: "academic", label: "Academic Seminars", count: 5 },
  { id: "sports", label: "Sports & E-sports", count: 3 },
]

export const CAMPUSES = [
  { id: "all", label: "All Campuses" },
  { id: "hanoi", label: "FPT Hanoi" },
  { id: "danang", label: "FPT Da Nang" },
  { id: "hcm", label: "FPT Ho Chi Minh" },
]
